name: build_openlist

on:
  # 支持手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24.1
          cache-dependency-path: ${{ github.workspace }}/AListLib/go.sum

      - name: checkout_code
        uses: actions/checkout@v3

      - name: build openlist aar
        run: |
          cd $GITHUB_WORKSPACE/AListLib/scripts
          sh install_alist.sh
          sh install_gomobile.sh
          sh build_aar.sh
          cp -f $GITHUB_WORKSPACE/AListLib/sources/alistlib.aar $GITHUB_WORKSPACE/app/libs          
          
